version: '3.8'
services:
  wallet:
    build: /
    image: wallet-service
    container_name: wallet-server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - BD=jdbc:postgresql://db:5432/postgres_wallet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
  db:
    image: postgres:16
    container_name: wallet_postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres_wallet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - DB_HOST=db
      - DB_PORT=5432
